services:
  web:
    build:  
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: kara-local
    restart: "unless-stopped"
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.django
    ports:
      - 8000:8000

volumes:
  web:
