# Generated by Django 5.1.7 on 2025-04-03 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kara.accounts.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=kara.accounts.fields.DefaultOneToOneField(
                create=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
