# Generated by Django 5.1.7 on 2025-04-01 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import kara.accounts.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_email_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=kara.accounts.fields.DefaultOneToOneField(
                create=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
