# Generated by Django 5.1.7 on 2025-04-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_email_confirmed_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio_image",
            field=models.ImageField(
                default="/profile/profile_default_image.png", upload_to=""
            ),
        ),
    ]
