# Generated by Django 5.1.7 on 2025-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userprofile_bio_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio_image",
            field=models.ImageField(
                default="/media/profile/profile_default_image.png", upload_to=""
            ),
        ),
    ]
