# Generated by Django 5.1.7 on 2025-05-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_bio_alter_userprofile_bio_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio_image",
            field=models.ImageField(
                default="profile/profile_default_image.png", upload_to=""
            ),
        ),
    ]
