# Generated by Django 5.1.7 on 2025-05-23 07:34

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashgift",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="cashgift",
            name="price",
            field=models.PositiveIntegerField(verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="cashgift",
            name="receipt_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date of receipt"
            ),
        ),
        migrations.AlterField(
            model_name="weddinggiftregistry",
            name="in_kind_gifts_allow",
            field=models.BooleanField(
                default=True,
                help_text="Specifies whether to include the details of in-kind gift received.",
                verbose_name="include in-kind gifts",
            ),
        ),
        migrations.AlterField(
            model_name="weddinggiftregistry",
            name="receiver",
            field=models.CharField(
                help_text="This is the person who is getting married and receiving the wedding gift.",
                max_length=64,
                verbose_name="receiver",
            ),
        ),
        migrations.AlterField(
            model_name="weddinggiftregistry",
            name="receptionist",
            field=models.CharField(
                help_text="This is the person who recorded the wedding gift receipt details.",
                max_length=64,
                verbose_name="receptionist",
            ),
        ),
        migrations.AlterField(
            model_name="weddinggiftregistry",
            name="wedding_date",
            field=models.DateField(verbose_name="wedding date"),
        ),
        migrations.CreateModel(
            name="GiftTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cashgift",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="cash_gifts",
                to="wedding_gifts.gifttag",
                verbose_name="tags",
            ),
        ),
        migrations.AddConstraint(
            model_name="gifttag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("owner"),
                name="unique_lower_name_owner",
            ),
        ),
    ]
