# Generated by Django 5.1.7 on 2025-05-24 02:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0002_alter_cashgift_name_alter_cashgift_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weddinggiftregistry",
            name="in_kind_gifts_allow",
        ),
        migrations.CreateModel(
            name="WeddingGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[("cash", "Cash"), ("non_cash", "Non-cash")]
                    ),
                ),
                (
                    "non_cash_detail",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("price", models.PositiveIntegerField(verbose_name="price")),
                (
                    "receipt_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="date of receipt",
                    ),
                ),
                (
                    "registry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_gifts",
                        to="wedding_gifts.weddinggiftregistry",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wedding_gifts",
                        to="wedding_gifts.gifttag",
                        verbose_name="tags",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CashGift",
        ),
        migrations.AddConstraint(
            model_name="weddinggift",
            constraint=models.CheckConstraint(
                condition=models.Q(("non_cash_detail__isnull", True)),
                name="cash_no_detail",
            ),
        ),
    ]
