# Generated by Django 5.1.7 on 2025-05-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0002_alter_cashgift_name_alter_cashgift_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashgift",
            options={"default_related_name": "cash_gifts"},
        ),
        migrations.AlterField(
            model_name="cashgift",
            name="registry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wedding_gifts.weddinggiftregistry",
            ),
        ),
        migrations.AlterField(
            model_name="cashgift",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="wedding_gifts.gifttag", verbose_name="tags"
            ),
        ),
    ]
