# Generated by Django 5.1.7 on 2025-05-27 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wedding_gifts",
            "0003_alter_cashgift_options_alter_cashgift_registry_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InKindGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                ("price", models.PositiveIntegerField(verbose_name="price")),
                (
                    "receipt_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="date of receipt",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("appliance", "Appliance"),
                            ("kitchenware", "Kitchenware"),
                            ("furniture", "Furniture"),
                            ("decor", "Decor"),
                            ("bedding", "Bedding"),
                            ("food_or_drink", "Food or Drink"),
                            ("daily_goods", "Daily Goods"),
                            ("other", "Other"),
                        ]
                    ),
                ),
                ("kind_detail", models.CharField(max_length=128, null=True)),
                (
                    "registry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wedding_gifts.weddinggiftregistry",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="wedding_gifts.gifttag", verbose_name="tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "In-kind gift",
                "verbose_name_plural": "In-kind gifts",
                "default_related_name": "in_kind_gifts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind__exact", "other"), _negated=True),
                            ("kind_detail__isnull", False),
                            _connector="OR",
                        ),
                        name="kind_other_require_detail",
                    )
                ],
            },
        ),
    ]
