# Generated by Django 5.1.7 on 2025-05-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0004_inkindgift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inkindgift",
            name="kind",
            field=models.CharField(
                choices=[
                    ("appliance", "Appliance"),
                    ("kitchenware", "Kitchenware"),
                    ("furniture", "Furniture"),
                    ("decor", "Decor"),
                    ("bedding", "Bedding"),
                    ("food_or_drink", "Food or Drink"),
                    ("daily_goods", "Daily Goods"),
                    ("other", "Other"),
                ],
                default="appliance",
            ),
        ),
    ]
