# Generated by Django 5.1.7 on 2025-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0005_alter_inkindgift_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inkindgift",
            name="kind",
            field=models.CharField(
                choices=[
                    ("appliance", "Appliance"),
                    ("kitchenware", "Kitchenware"),
                    ("furniture", "Furniture"),
                    ("decor", "Decor"),
                    ("bedding", "Bedding"),
                    ("food_or_drink", "Food or Drink"),
                    ("daily_goods", "Daily Goods"),
                    ("other", "Other"),
                ],
                default="appliance",
                verbose_name="Gift Kind",
            ),
        ),
        migrations.AlterField(
            model_name="inkindgift",
            name="kind_detail",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Gift Detail"
            ),
        ),
    ]
