# Generated by Django 5.1.7 on 2025-06-18 07:08

import django.core.validators
from django.db import migrations, models

import kara.wedding_gifts.models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0005_alter_inkindgift_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="gifttag",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gifttag",
            name="hex_color",
            field=models.CharField(
                default=kara.wedding_gifts.models.get_random_hex_color,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=0,
                        message="It is not in hex color code format.",
                        regex="^#[0-9A-F]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="inkindgift",
            name="kind",
            field=models.CharField(
                choices=[
                    ("appliance", "Appliance"),
                    ("kitchenware", "Kitchenware"),
                    ("furniture", "Furniture"),
                    ("decor", "Decor"),
                    ("bedding", "Bedding"),
                    ("food_or_drink", "Food or Drink"),
                    ("daily_goods", "Daily Goods"),
                    ("other", "Other"),
                ],
                default="appliance",
                verbose_name="Gift Kind",
            ),
        ),
        migrations.AlterField(
            model_name="inkindgift",
            name="kind_detail",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Gift Detail"
            ),
        ),
    ]
