# Generated by Django 5.1.7 on 2025-06-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0006_gifttag_description_gifttag_hex_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gifttag",
            options={"verbose_name": "Tag"},
        ),
    ]
