# Generated by Django 5.1.7 on 2025-07-03 10:02

from django.db import migrations, models

import kara.wedding_gifts.models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0007_alter_gifttag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="weddinggiftregistry",
            name="cover_image",
            field=models.CharField(
                default=kara.wedding_gifts.models.get_random_registry_image,
                max_length=256,
            ),
        ),
    ]
