# Generated by Django 5.1.7 on 2025-07-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_gifts", "0008_weddinggiftregistry_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weddinggiftregistry",
            name="in_kind_gifts_allow",
        ),
    ]
