# Generated by Django 5.1.7 on 2025-05-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashGiftsRecordRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("Groom", "Groom's side"), ("Bride", "Bride's side")]
                    ),
                ),
                ("honoree", models.CharField(max_length=64)),
                ("receptionist", models.CharField(max_length=64)),
                ("wedding_date", models.DateField()),
                ("updated_at", models.DateField(auto_now=True)),
                ("in_kind_gifts_allow", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_gifts_record_repository",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
