# Generated by Django 5.1.7 on 2025-05-17 05:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashGiftsRecordRepository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("Groom", "Groom's side"), ("Bride", "Bride's side")],
                        default="Groom",
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        help_text="This is the person who is getting married and receiving the cash gifts.",
                        max_length=64,
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "receptionist",
                    models.CharField(
                        help_text="This is the person who recorded the cash gifts receipt details.",
                        max_length=64,
                        verbose_name="Receptionist",
                    ),
                ),
                ("wedding_date", models.DateField(verbose_name="Wedding Date")),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "in_kind_gifts_allow",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether to include the details of in-kind gifts received.",
                        verbose_name="Include In-Kind Gifts",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_gifts_record_repository",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashGifts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("price", models.PositiveIntegerField(verbose_name="Price")),
                (
                    "receipt_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date of Receipt",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_gift_records",
                        to="cash_gifts.cashgiftsrecordrepository",
                    ),
                ),
            ],
        ),
    ]
