# Generated by Django 5.1.7 on 2025-05-13 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashGiftsRecordRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("Groom", "Groom's side"), ("Bride", "Bride's side")],
                        default="Groom",
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        help_text="This is the person who is getting married and receiving the cash gifts.",
                        max_length=64,
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "receptionist",
                    models.CharField(
                        help_text="This is the person who recorded the cash gifts receipt details.",
                        max_length=64,
                        verbose_name="Receptionist",
                    ),
                ),
                ("wedding_date", models.DateField(verbose_name="Wedding Date")),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "in_kind_gifts_allow",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether to include the details of in-kind gifts received.",
                        verbose_name="Include In-Kind Gifts",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_gifts_record_repository",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
