# Generated by Django 5.1.7 on 2025-05-14 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_gifts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashGifts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("price", models.PositiveIntegerField()),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cash_gifts.cashgiftsrecordrepository",
                    ),
                ),
            ],
        ),
    ]
