# Generated by Django 5.1.7 on 2025-05-16 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_gifts", "0002_cashgifts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashgifts",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="cashgifts",
            name="receipt_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date of Receipt"
            ),
        ),
        migrations.AlterField(
            model_name="cashgifts",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="cashgifts",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Price"),
        ),
    ]
